langlanguage: c

python:
  - "2.7"

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

before_install:
  - export CC=gcc
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - luarocks install lake

script:
  - lake test

notifications:
  email:
    on_success: change
    on_failure: always